// src/components/ui/stack-card.tsx
import { Icon } from "@iconify/react"
import { motion } from "framer-motion"
import { useLocale } from "next-intl"
import { Merriweather } from "next/font/google"
import Link from "next/link"

const merriweather = Merriweather({ subsets: ["latin"], weight: "900" })

export default function StackCard({ name, icon, link, description }: Readonly<StackCardProps>) {
	const locale = useLocale()

	return (
		<motion.div
			initial={{ opacity: 0 }}
			whileInView={{ opacity: 1 }}
			whileHover={{ scale: 1.02, transition: { duration: 0.4 } }}
			transition={{ duration: 0.6 }}
			viewport={{ once: true }}
			className="card flex min-h-[145px] flex-col items-center gap-2 p-2 text-center sm:min-h-[130px] sm:p-4 md:p-4 lg:min-h-[160px] xl:min-h-[130px]"
		>
			<Link href={link} title={link} target="_blank" rel="noopener noreferrer">
				<Icon icon={icon} width={25} height={25} className="scale" />
			</Link>

			<h5 className={merriweather.className}>{name}</h5>

			<span className="flex-grow text-xs text-muted-foreground">{description[locale]}</span>
		</motion.div>
	)
}

// app/components/ui/stack-card.vue
<template>
  <div
    v-motion :initial="{ opacity: 0 }"
    :visible="{ opacity: 1 }" :duration="800"
    class="card flex min-h-[145px] flex-col items-center justify-center gap-2 text-center md:min-h-[205px] xl:min-h-0"
  >
    <nuxt-link
      :to="stackItem.link" :title="stackItem.link"
      target="_blank" rel="noopener noreferrer"
      class="hover:scale flex items-center rounded-full p-2 transition-all hover:bg-muted"
    >
      <icon :name="stackItem.icon" size="25" />
    </nuxt-link>

    <h5 class="font-serif">
      {{ stackItem.name }}
    </h5>

    <span class="flex-grow text-center text-sm text-muted-foreground md:text-xs">
      {{ stackItem.description }}
    </span>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  stackItem: {
    name: string
    icon: string
    link: string
    description: string
  }
}>()
</script>
