// src/components/About.tsx
import { Icon } from "@iconify/react"
import { useLocale } from "next-intl"
import { Merriweather } from "next/font/google"
import Link from "next/link"
import aboutData from "../data/about.json"

const merriweather = Merriweather({ subsets: ["latin"], weight: "900" })

export default function About() {
	const locale = useLocale()

	const {
		aboutTitle,
		aboutSection1,
		aboutSection2,
		githubLabel,
		github,
		linkedinLabel,
		linkedin,
		emailLabel,
		email,
		resumeEn,
		resumePt
	} = aboutData

	return (
		<section id="about" className="flex-1 text-center md:text-start">
			<h3 className={`${merriweather.className} my-8`}>{aboutTitle[locale]}</h3>

			<div className="space-y-6">
				<p className="text-sm text-muted-foreground md:text-sm">{aboutSection1[locale]}</p>
				<hr />
				<p className="text-sm text-muted-foreground md:text-sm">{aboutSection2[locale]}</p>
				<hr />

				<div id="contact" className="flex flex-col items-center justify-center gap-4 text-sm md:items-start">
					<p className="flex flex-row items-center gap-2 font-semibold italic">
						<Icon icon="simple-icons:github" width={20} height={20} className="scale" />
						{githubLabel}
						<Link href="https://github.com/matimortari" className="text-secondary hover:underline">
							{github}
						</Link>
					</p>
					<p className="flex flex-row items-center gap-2 font-semibold italic">
						<Icon icon="simple-icons:linkedin" width={20} height={20} className="scale" />
						{linkedinLabel}
						<Link href="https://linkedin.com/in/matheus-mortari-19rt" className="text-secondary hover:underline">
							{linkedin}
						</Link>
					</p>
					<p className="flex flex-row items-center gap-2 font-semibold italic">
						<Icon icon="simple-icons:gmail" width={20} height={20} className="scale" />
						{emailLabel}
						<Link href="mailto:matheus.felipe.19rt@gmail.com" className="text-secondary hover:underline">
							{email}
						</Link>
					</p>
				</div>

				<div className="my-4 flex flex-col items-center justify-center gap-4 md:flex-row md:justify-end">
					<Link href="https://matimortari.github.io/assets/cv-en.pdf" className="btn">
						<Icon icon="material-symbols:article-shortcut" width={25} height={25} className="scale" />
						{resumeEn[locale]}
					</Link>
					<Link href="https://matimortari.github.io/assets/cv-pt.pdf" className="btn">
						<Icon icon="material-symbols:article-shortcut" width={25} height={25} className="scale" />
						{resumePt[locale]}
					</Link>
				</div>
			</div>
		</section>
	)
}

// src/components/About.vue
<template>
  <section id="about" class="flex-1 text-center lg:text-start">
    <h3
      v-motion :initial="{ opacity: 0, y: -20 }" :visible="{ opacity: 1, y: 0 }" :duration="400"
      class="font-serif my-10"
    >
      {{ t("index.about.title") }}
    </h3>

    <div
      v-for="(section, index) in sections" :key="index" v-motion :initial="{ opacity: 0, x: -20 }"
      :visible="{ opacity: 1, x: 0 }" :duration="400"
    >
      <p class="text-sm text-muted-foreground lg:text-sm my-4">
        {{ t(section) }}
      </p>
      <hr v-if="index < sections.length - 1">
    </div>

    <hr class="my-4">

    <div id="contact" class="flex flex-col items-center justify-center gap-4 text-sm lg:items-start">
      <h4
        v-motion :initial="{ opacity: 0, y: -10 }" :visible="{ opacity: 1, y: 0 }" :duration="400"
        class="font-serif text-lg"
      >
        {{ t("index.about.contact") }}
      </h4>

      <p
        v-for="(contact, index) in contacts" :key="index" v-motion :initial="{ opacity: 0, x: -20 }"
        :visible="{ opacity: 1, x: 0 }" :duration="400" :delay="200 * Number(index)"
        class="flex flex-row items-center gap-2 font-semibold italic"
      >
        <Icon :name="contact.icon" size="20" class="animate-scale" />
        {{ contact.label }}
        <a :href="contact.href" class="text-secondary hover:underline" target="_blank">{{ contact.text }}</a>
      </p>
    </div>

    <hr class="my-4">

    <div
      v-motion :initial="{ opacity: 0, y: 20 }" :visible="{ opacity: 1, y: 0 }" :duration="400" :delay="400"
      class="flex flex-col items-center justify-center gap-4 lg:flex-row lg:justify-end"
    >
      <a v-for="(resume, index) in resumes" :key="index" :href="resume.href" class="btn" target="_blank">
        <Icon name="material-symbols:article-shortcut" size="25" class="animate-scale" />
        {{ t(resume.label) }}
      </a>
    </div>
  </section>
</template>

<script setup lang="ts">
const { t } = useI18n()

const sections = [
  "index.about.section1",
  "index.about.section2",
]

const contacts = [
  {
    icon: "simple-icons:github",
    label: "GitHub",
    text: "/matimortari",
    href: "https://github.com/matimortari",
  },
  {
    icon: "simple-icons:linkedin",
    label: "LinkedIn",
    text: "/matheus-mortari-19rt",
    href: "https://linkedin.com/in/matheus-mortari-19rt",
  },
  {
    icon: "simple-icons:gmail",
    label: "Email",
    text: "matheus.felipe.19rt@gmail.com",
    href: "mailto:matheus.felipe.19rt@gmail.com",
  },
]

const resumes = [
  {
    label: "index.about.resumeEn",
    href: "https://matimortari.github.io/assets/cv/cv-en.pdf",
  },
  {
    label: "index.about.resumePt",
    href: "https://matimortari.github.io/assets/cv/cv-pt.pdf",
  },
]
</script>
