// src/components/Hero.tsx
import heroData from "@/src/data/hero.json"
import { Icon } from "@iconify/react"
import { motion } from "framer-motion"
import { useLocale } from "next-intl"
import { Merriweather } from "next/font/google"
import Image from "next/image"
import Link from "next/link"

const merriweather = Merriweather({ subsets: ["latin"], weight: "900" })

export default function Hero() {
	const locale = useLocale()

	const { title, subtitle, description } = heroData

	return (
		<section id="hero" className="relative flex min-h-screen items-center justify-center">
			<div className="hero-background" />

			<div className="hero-map scroll absolute inset-x-0 bottom-0 z-0 overflow-hidden opacity-20">
				<Image src="/map.png" alt="" className="hidden size-full md:block" width={800} height={800} />
				<Image src="/map.png" alt="" className="hidden size-full md:block" width={800} height={800} />
			</div>

			<div className="relative flex flex-col items-center gap-4 p-16">
				<motion.div initial={{ opacity: 0, y: -40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
					<Image src="/avatar.png" alt="Avatar" priority={true} width={150} height={150} className="float avatar" />
				</motion.div>

				<motion.div
					initial={{ opacity: 0, y: 40 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 1 }}
					className="my-4 flex flex-col gap-4 text-center md:gap-2"
				>
					<h1 className={merriweather.className}>{title[locale]}</h1>
					<h2 className={merriweather.className}>{subtitle[locale]}</h2>
				</motion.div>

				<motion.p
					initial={{ opacity: 0, y: 40 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 1 }}
					className="max-w-sm text-center text-sm text-muted-foreground md:text-base"
				>
					{description[locale]}
				</motion.p>

				<motion.div
					initial={{ opacity: 0, y: 40 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 1, delay: 0.6 }}
					className="my-4 flex flex-row items-center justify-center gap-6 text-secondary"
				>
					<Link href="https://github.com/matimortari" title="GitHub">
						<Icon icon="simple-icons:github" width={25} height={25} className="scale" />
					</Link>
					<Link href="https://linkedin.com/in/matheus-mortari-19rt" title="LinkedIn">
						<Icon icon="simple-icons:linkedin" width={25} height={25} className="scale" />
					</Link>
					<Link href="mailto:matheus.felipe.19rt@gmail.com" title="Email">
						<Icon icon="simple-icons:gmail" width={25} height={25} className="scale" />
					</Link>
				</motion.div>
			</div>
		</section>
	)
}

// src/components/Hero.vue
<template>
  <section id="hero" class="relative flex min-h-screen items-center justify-center overflow-hidden">
    <div class="hero-background" />

    <div class="animate-scroll absolute inset-x-0 bottom-0 z-0 flex w-[200%] overflow-hidden opacity-20">
      <img
        src="/map.png" alt="Background Image"
        class="hidden size-full lg:block" width="800"
        height="800"
      >
      <img
        src="/map.png" alt="Background Image"
        class="hidden size-full lg:block" width="800"
        height="800"
      >
    </div>

    <div
      v-motion :initial="{ opacity: 0, y: -40 }"
      :visible="{ opacity: 1, y: 0 }" :transition="{ duration: 800 }"
      class="relative flex flex-col items-center gap-2 px-4 pb-12 pt-24"
    >
      <div class="relative size-36 lg:size-40 2xl:size-44">
        <img src="/avatar.png" alt="Avatar" class="avatar animate-float absolute inset-0">
      </div>

      <div class="m-4 flex flex-col gap-2 text-center">
        <h1 class="font-serif text-3xl xl:text-4xl">
          {{ t("index.hero.title") }}
        </h1>
        <h2 class="font-serif text-xl xl:text-2xl">
          {{ t("index.hero.subtitle") }}
        </h2>
      </div>

      <div class="flex flex-col items-center justify-center px-10">
        <p class="max-w-md text-center leading-5 text-muted-foreground">
          {{ t("index.hero.description") }}
        </p>

        <div class="my-4 flex flex-row items-center justify-center gap-4 text-secondary lg:my-8">
          <a
            v-for="link in socialLinks" :key="link.href"
            :href="link.href" :title="link.title"
            target="_blank"
          >
            <Icon :name="link.icon" size="25" class="animate-scale" />
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const { t } = useI18n()

const socialLinks = [
  { href: "https://github.com/matimortari", icon: "simple-icons:github", title: "GitHub" },
  { href: "https://linkedin.com/in/matheus-mortari-19rt", icon: "simple-icons:linkedin", title: "LinkedIn" },
  { href: "mailto:matheus.felipe.19rt@gmail.com", icon: "simple-icons:gmail", title: "Email" },
]
</script>
