// src/components/Navbar.vue
<template>
  <nav
    class="fixed top-0 z-50 w-full rounded-lg px-6 py-2 backdrop-blur transition-transform duration-300" :class="[
      showNavbar ? 'translate-y-0' : '-translate-y-full',
    ]"
  >
    <div class="flex flex-row items-center justify-between">
      <div
        v-motion :initial="{ opacity: 0 }" :visible="{ opacity: 1 }" :duration="200"
        class="flex flex-row items-center justify-center gap-10 text-foreground"
      >
        <NuxtLink to="/">
          <img
            v-motion :initial="{ opacity: 0 }" :visible="{ opacity: 1 }" :duration="200" :delay="400" src="/logo.png"
            alt="Logo" class="animate-scale" width="35" height="35"
          >
        </NuxtLink>

        <div class="flex flex-row items-center gap-8 font-semibold tracking-wide">
          <NuxtLink
            v-motion :initial="{ opacity: 0, x: -20 }" :visible="{ opacity: 1, x: 0 }" :duration="200"
            :delay="200" to="#about" class="hidden hover:underline sm:block"
          >
            {{ t("index.navbar.about") }}
          </NuxtLink>
          <NuxtLink
            v-motion :initial="{ opacity: 0, x: -20 }" :visible="{ opacity: 1, x: 0 }" :duration="200"
            :delay="200" to="#projects" class="hidden hover:underline sm:block"
          >
            {{ t("index.navbar.projects") }}
          </NuxtLink>
          <NuxtLink
            v-motion :initial="{ opacity: 0, x: -20 }" :visible="{ opacity: 1, x: 0 }" :duration="200"
            :delay="200" to="#contact" class="hidden hover:underline sm:block"
          >
            {{ t("index.navbar.contact") }}
          </NuxtLink>
        </div>
      </div>

      <div
        v-motion :initial="{ opacity: 0 }" :visible="{ opacity: 1 }" :duration="200" :delay="400"
        class="flex flex-row items-center gap-4 font-semibold"
      >
        <button v-for="language in availableLocales" :key="language" @click="() => setLanguage(language)">
          {{ t(`locale.${language}`) }}
        </button>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
const { t, locale, availableLocales } = useI18n()

const showNavbar = ref(true)
let lastScrollY = 0

function handleScroll() {
  const currentY = window.scrollY
  showNavbar.value = currentY < lastScrollY || currentY < 10
  lastScrollY = currentY
}

onMounted(async () => {
  const savedLang = localStorage.getItem("nuxt-lang")
  if (savedLang) {
    locale.value = savedLang
    await nextTick()
    document.documentElement.dir = t("locale.dir")
  }

  lastScrollY = window.scrollY
  window.addEventListener("scroll", handleScroll)
})

onBeforeUnmount(() => {
  window.removeEventListener("scroll", handleScroll)
})

async function setLanguage(language: string) {
  locale.value = language
  localStorage.setItem("nuxt-lang", language)
  await nextTick()
  document.documentElement.dir = t("locale.dir")
}
</script>

// src/components/navbar.tsx
"use client"

import navbar from "@/src/json/navbar.json"
import { motion } from "framer-motion"
import { useLocale } from "next-intl"
import Image from "next/image"
import Link from "next/link"

export default function Navbar() {
  const locale = useLocale()

  const { about, projects, contact } = navbar

  return (
    <nav className="fixed top-0 z-50 w-full rounded-lg px-6 py-2 backdrop-blur">
      <div className="flex flex-row items-center justify-between">
        <div className="flex flex-row items-center justify-center gap-10 text-foreground">
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.8 }}>
            <Link href="/">
              <Image src="/logo.png" alt="Logo" className="scale" width={35} height={35} />
            </Link>
          </motion.div>

          <div className="flex flex-row items-center gap-8 font-semibold">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
            >
              <Link href="#about" className="hidden hover:underline sm:block">
                {about[locale]}
              </Link>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
            >
              <Link href="#projects" className="hidden hover:underline sm:block">
                {projects[locale]}
              </Link>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.6 }}
            >
              <Link href="#contact" className="hidden hover:underline sm:block">
                {contact[locale]}
              </Link>
            </motion.div>
          </div>
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 2 }}
          className="flex flex-row items-center gap-4 font-bold"
        >
          <Link href="/en" title="English - US" className="hover:underline">
            EN
          </Link>
          <Link href="/pt" title="Português - BR" className="hover:underline">
            PT
          </Link>
        </motion.div>
      </div>
    </nav>
  )
}
