// src/components/Projects.tsx
import { useTranslations } from "next-intl"
import projectsData from "../data/projectsData.json"
import ProjectCard from "./ui/ProjectCard"

export default function ProjectsSection() {
	const t = useTranslations("Projects")

	return (
		<section id="projects" className="w-full p-4 text-center">
			<h3 className="my-4">{t("title")}</h3>

			<div className="my-8 flex flex-col justify-center gap-4 md:flex-row md:gap-12">
				{projectsData.map((project) => (
					<ProjectCard
						key={project.title}
						title={project.title}
						description={project.description}
						skills={project.skills}
						source={project.source}
						link={project.link}
					/>
				))}
			</div>
		</section>
	)
}

// src/components/Projects.vue
<template>
  <section id="projects" class="flex-1 text-center">
    <h3
      v-motion :initial="{ opacity: 0, y: -20 }"
      :visible="{ opacity: 1, y: 0 }" :duration="400"
      class="font-serif my-10"
    >
      {{ t("index.projects.title") }}
    </h3>

    <div
      v-motion :initial="{ opacity: 0, y: -40 }"
      :visible="{ opacity: 1, y: 0 }" :duration="400"
      :delay="200"
      class="flex w-full flex-col justify-center gap-12 lg:flex-row xl:gap-40"
    >
      <UiProjectCard
        v-for="(project, index) in projects"
        :key="project.title"
        v-motion
        :initial="{ opacity: 0, y: 40 }"
        :visible="{ opacity: 1, y: 0 }"
        :duration="200" :delay="100 * Number(index)"
        :title="project.title"
        :description="project.description" :image="project.image"
        :skills="project.skills" :source="project.source"
        :link="project.link"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
const { t, tm } = useI18n()

const projects = computed(() => tm("index.projects.items"))
</script>
