// src/components/Stack.vue
<template>
  <section id="stack" class="flex-1 text-center lg:text-start">
    <h3
      v-motion :initial="{ opacity: 0, y: -20 }" :visible="{ opacity: 1, y: 0 }" :duration="800"
      class="font-serif my-10"
    >
      {{ t("index.stack.title") }}
    </h3>

    <div
      v-motion :initial="{ opacity: 0, y: -40 }" :visible="{ opacity: 1, y: 0 }" :duration="400" :delay="200"
      class="grid grid-cols-2 gap-2 lg:grid-cols-3"
    >
      <UiStackCard
        v-for="(item, index) in stackItems"
        :key="item.name"
        v-motion
        :name="item.name"
        :icon="item.icon"
        :link="item.link"
        :description="item.description"
        :initial="{ opacity: 0, y: 20 }"
        :visible="{ opacity: 1, y: 0 }"
        :duration="200"
        :delay="100 * Number(index)"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
const { t, tm } = useI18n()

const stackItems = computed(() => tm("index.stack.items"))
</script>

// src/components/Stack.tsx
import { useTranslations } from "next-intl"
import stackData from "../data/stackData.json"
import StackCard from "./ui/StackCard"

export default function Stack() {
	const t = useTranslations("Stack")

	return (
		<section id="stack" className="flex-1 text-center md:text-start">
			<h3 className="my-4">{t("title")}</h3>

			<div className="my-8 grid grid-cols-1 gap-4 md:grid-cols-3">
				{stackData.map((item) => (
					<StackCard
						key={item.name}
						name={item.name}
						icon={item.icon}
						link={item.link}
						description={item.description}
					/>
				))}
			</div>
		</section>
	)
}
