// src/components/ui/ProjectCard.tsx
import { Icon } from "@iconify/react"
import { useLocale } from "next-intl"
import { Merriweather } from "next/font/google"
import Image from "next/image"
import Link from "next/link"

const merriweather = Merriweather({ subsets: ["latin"], weight: "900" })

export default function ProjectCard({ title, description, image, skills, source, link }: Readonly<ProjectCardProps>) {
	const locale = useLocale()

	return (
		<div className="flex flex-col items-start gap-2 text-start">
			<Image src={image} alt={title} width={480} height={200} className="rounded-lg border" />

			<div className="my-1 flex flex-row items-center gap-4">
				<h4 className={merriweather.className}>{title}</h4>

				<div className="flex flex-row items-center gap-2">
					<Link href={source} title={source} target="_blank" rel="noopener noreferrer">
						<Icon icon="simple-icons:github" width={25} height={25} className="scale" />
					</Link>
					<Link href={link} title={link} target="_blank" rel="noopener noreferrer">
						<Icon icon="material-symbols:captive-portal" width={30} height={30} className="scale" />
					</Link>
				</div>
			</div>

			<div className="flex max-w-sm flex-wrap gap-1">
				{skills.map((skills) => (
					<span key={skills} className="text-primary-foreground rounded-full bg-accent px-2 py-1 text-xs font-semibold">
						{skills}
					</span>
				))}
			</div>

			<p className="max-w-md text-sm text-muted-foreground">{description[locale]}</p>
		</div>
	)
}

// src/components/ui/project-card.vue
<template>
  <div
    v-motion :initial="{ opacity: 0 }"
    :visible="{ opacity: 1 }" :transition="{ duration: 400 }"
    class="flex flex-col items-center gap-2 text-center lg:items-start lg:text-start"
  >
    <img
      :src="image" :alt="title"
      width="600" height="320"
      class="card p-0"
    >

    <div
      v-motion :initial="{ opacity: 0, x: -20 }"
      :visible="{ opacity: 1, x: 0 }" :transition="{ duration: 400 }"
      class="my-1 flex flex-row items-center gap-4"
    >
      <h4 class="font-serif">
        {{ title }}
      </h4>

      <div class="flex flex-row items-center gap-2">
        <a :href="source" :title="source" target="_blank" rel="noopener noreferrer">
          <Icon name="simple-icons:github" size="25" class="animate-scale" />
        </a>
        <a :href="link" :title="link" target="_blank" rel="noopener noreferrer">
          <Icon name="material-symbols:captive-portal" size="25" class="animate-scale" />
        </a>
      </div>
    </div>

    <div
      v-motion :initial="{ opacity: 0, y: -20 }"
      :visible="{ opacity: 1, y: 0 }" :transition="{ duration: 400 }"
      class="flex  flex-wrap justify-center gap-1 lg:justify-start"
    >
      <span v-for="skill in skills" :key="skill" class="rounded-full bg-accent px-2 py-1 text-xs font-semibold">
        {{ skill }}
      </span>
    </div>

    <p
      v-motion :initial="{ opacity: 0, x: 20 }"
      :visible="{ opacity: 1, x: 0 }" :transition="{ duration: 400 }"
      class="max-w-xl text-sm text-muted-foreground"
    >
      {{ description }}
    </p>
  </div>
</template>

<script setup lang="ts">
defineProps({
  title: { type: String, required: true },
  description: { type: String, required: true },
  image: { type: String, required: true },
  source: { type: String, required: true },
  link: { type: String, required: true },
  skills: { type: Array as () => string[], required: true },
})
</script>
